### ISSUE TITLE
Installation failed on Windows.

### ISSUE THREAD

**Issue by BubblyBumblebee** [stetre/moonsc#2]
I setup the build environment like the documentation described, then ran the `make` and `make install` commands.

This works fine on my Linux virtual machine. However, neither of the commands work on my Windows 10 machine. Instead, I get this error.

![image](https://user-images.githubusercontent.com/13389117/72065313-90e1da00-32a3-11ea-87f9-cb145c2791c2.png)

It looks like it's expecting certain files to be available, but for one reason or another they aren't present.

**Comment by stetre** [comment]
Hi, are you using MSYS2? From your screenshot it seems that the MINGW_PREFIX environment variable is not defined, so the Makefile thinks that it is compiling under Linux.

**Comment by BubblyBumblebee** [comment]
Oh, I see. Thank you.

I went and reinstalled MSYS2 and tried installing through there. Now I'm getting this error.

![image](https://user-images.githubusercontent.com/13389117/72136561-aeb84900-334e-11ea-8eb7-3ce32265d19d.png)

**Comment by stetre** [comment]
The latest commit should fix this error. Let me know if it works.

**Comment by BubblyBumblebee** [comment]
That works! Thank you so much.
